// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ccx

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Do(ctx context.Context, method string, path string, body any) (*http.Response, error) {
	ret := _mock.Called(ctx, method, path, body)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) (*http.Response, error)); ok {
		return returnFunc(ctx, method, path, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) *http.Response); ok {
		r0 = returnFunc(ctx, method, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, any) error); ok {
		r1 = returnFunc(ctx, method, path, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHTTPClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - body any
func (_e *MockHTTPClient_Expecter) Do(ctx interface{}, method interface{}, path interface{}, body interface{}) *MockHTTPClient_Do_Call {
	return &MockHTTPClient_Do_Call{Call: _e.mock.On("Do", ctx, method, path, body)}
}

func (_c *MockHTTPClient_Do_Call) Run(run func(ctx context.Context, method string, path string, body any)) *MockHTTPClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Do_Call) Return(response *http.Response, err error) *MockHTTPClient_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_Do_Call) RunAndReturn(run func(ctx context.Context, method string, path string, body any) (*http.Response, error)) *MockHTTPClient_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Get(ctx context.Context, path string, target any) error {
	ret := _mock.Called(ctx, path, target)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, path, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - target any
func (_e *MockHTTPClient_Expecter) Get(ctx interface{}, path interface{}, target interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get", ctx, path, target)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(ctx context.Context, path string, target any)) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(err error) *MockHTTPClient_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(ctx context.Context, path string, target any) error) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatastoresService creates a new instance of MockDatastoresService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatastoresService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatastoresService {
	mock := &MockDatastoresService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatastoresService is an autogenerated mock type for the DatastoresService type
type MockDatastoresService struct {
	mock.Mock
}

type MockDatastoresService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatastoresService) EXPECT() *MockDatastoresService_Expecter {
	return &MockDatastoresService_Expecter{mock: &_m.Mock}
}

// ApplyParameterGroup provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) ApplyParameterGroup(ctx context.Context, id string, group string) error {
	ret := _mock.Called(ctx, id, group)

	if len(ret) == 0 {
		panic("no return value specified for ApplyParameterGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastoresService_ApplyParameterGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyParameterGroup'
type MockDatastoresService_ApplyParameterGroup_Call struct {
	*mock.Call
}

// ApplyParameterGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - group string
func (_e *MockDatastoresService_Expecter) ApplyParameterGroup(ctx interface{}, id interface{}, group interface{}) *MockDatastoresService_ApplyParameterGroup_Call {
	return &MockDatastoresService_ApplyParameterGroup_Call{Call: _e.mock.On("ApplyParameterGroup", ctx, id, group)}
}

func (_c *MockDatastoresService_ApplyParameterGroup_Call) Run(run func(ctx context.Context, id string, group string)) *MockDatastoresService_ApplyParameterGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastoresService_ApplyParameterGroup_Call) Return(err error) *MockDatastoresService_ApplyParameterGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastoresService_ApplyParameterGroup_Call) RunAndReturn(run func(ctx context.Context, id string, group string) error) *MockDatastoresService_ApplyParameterGroup_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) Create(ctx context.Context, c Datastore) (*Datastore, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Datastore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Datastore) (*Datastore, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Datastore) *Datastore); ok {
		r0 = returnFunc(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Datastore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Datastore) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastoresService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDatastoresService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c Datastore
func (_e *MockDatastoresService_Expecter) Create(ctx interface{}, c interface{}) *MockDatastoresService_Create_Call {
	return &MockDatastoresService_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockDatastoresService_Create_Call) Run(run func(ctx context.Context, c Datastore)) *MockDatastoresService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Datastore
		if args[1] != nil {
			arg1 = args[1].(Datastore)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastoresService_Create_Call) Return(datastore *Datastore, err error) *MockDatastoresService_Create_Call {
	_c.Call.Return(datastore, err)
	return _c
}

func (_c *MockDatastoresService_Create_Call) RunAndReturn(run func(ctx context.Context, c Datastore) (*Datastore, error)) *MockDatastoresService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastoresService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDatastoresService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDatastoresService_Expecter) Delete(ctx interface{}, id interface{}) *MockDatastoresService_Delete_Call {
	return &MockDatastoresService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDatastoresService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockDatastoresService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastoresService_Delete_Call) Return(err error) *MockDatastoresService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastoresService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockDatastoresService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) Read(ctx context.Context, id string) (*Datastore, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *Datastore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Datastore, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Datastore); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Datastore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastoresService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockDatastoresService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDatastoresService_Expecter) Read(ctx interface{}, id interface{}) *MockDatastoresService_Read_Call {
	return &MockDatastoresService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockDatastoresService_Read_Call) Run(run func(ctx context.Context, id string)) *MockDatastoresService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastoresService_Read_Call) Return(datastore *Datastore, err error) *MockDatastoresService_Read_Call {
	_c.Call.Return(datastore, err)
	return _c
}

func (_c *MockDatastoresService_Read_Call) RunAndReturn(run func(ctx context.Context, id string) (*Datastore, error)) *MockDatastoresService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// SetFirewallRules provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) SetFirewallRules(ctx context.Context, storeID string, firewalls []FirewallRule) error {
	ret := _mock.Called(ctx, storeID, firewalls)

	if len(ret) == 0 {
		panic("no return value specified for SetFirewallRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []FirewallRule) error); ok {
		r0 = returnFunc(ctx, storeID, firewalls)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastoresService_SetFirewallRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFirewallRules'
type MockDatastoresService_SetFirewallRules_Call struct {
	*mock.Call
}

// SetFirewallRules is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - firewalls []FirewallRule
func (_e *MockDatastoresService_Expecter) SetFirewallRules(ctx interface{}, storeID interface{}, firewalls interface{}) *MockDatastoresService_SetFirewallRules_Call {
	return &MockDatastoresService_SetFirewallRules_Call{Call: _e.mock.On("SetFirewallRules", ctx, storeID, firewalls)}
}

func (_c *MockDatastoresService_SetFirewallRules_Call) Run(run func(ctx context.Context, storeID string, firewalls []FirewallRule)) *MockDatastoresService_SetFirewallRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []FirewallRule
		if args[2] != nil {
			arg2 = args[2].([]FirewallRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastoresService_SetFirewallRules_Call) Return(err error) *MockDatastoresService_SetFirewallRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastoresService_SetFirewallRules_Call) RunAndReturn(run func(ctx context.Context, storeID string, firewalls []FirewallRule) error) *MockDatastoresService_SetFirewallRules_Call {
	_c.Call.Return(run)
	return _c
}

// SetMaintenanceSettings provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) SetMaintenanceSettings(ctx context.Context, storeID string, settings MaintenanceSettings) error {
	ret := _mock.Called(ctx, storeID, settings)

	if len(ret) == 0 {
		panic("no return value specified for SetMaintenanceSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MaintenanceSettings) error); ok {
		r0 = returnFunc(ctx, storeID, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastoresService_SetMaintenanceSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaintenanceSettings'
type MockDatastoresService_SetMaintenanceSettings_Call struct {
	*mock.Call
}

// SetMaintenanceSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - settings MaintenanceSettings
func (_e *MockDatastoresService_Expecter) SetMaintenanceSettings(ctx interface{}, storeID interface{}, settings interface{}) *MockDatastoresService_SetMaintenanceSettings_Call {
	return &MockDatastoresService_SetMaintenanceSettings_Call{Call: _e.mock.On("SetMaintenanceSettings", ctx, storeID, settings)}
}

func (_c *MockDatastoresService_SetMaintenanceSettings_Call) Run(run func(ctx context.Context, storeID string, settings MaintenanceSettings)) *MockDatastoresService_SetMaintenanceSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 MaintenanceSettings
		if args[2] != nil {
			arg2 = args[2].(MaintenanceSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastoresService_SetMaintenanceSettings_Call) Return(err error) *MockDatastoresService_SetMaintenanceSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastoresService_SetMaintenanceSettings_Call) RunAndReturn(run func(ctx context.Context, storeID string, settings MaintenanceSettings) error) *MockDatastoresService_SetMaintenanceSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDatastoresService
func (_mock *MockDatastoresService) Update(ctx context.Context, old Datastore, next Datastore) (*Datastore, error) {
	ret := _mock.Called(ctx, old, next)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Datastore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Datastore, Datastore) (*Datastore, error)); ok {
		return returnFunc(ctx, old, next)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Datastore, Datastore) *Datastore); ok {
		r0 = returnFunc(ctx, old, next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Datastore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Datastore, Datastore) error); ok {
		r1 = returnFunc(ctx, old, next)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastoresService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDatastoresService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - old Datastore
//   - next Datastore
func (_e *MockDatastoresService_Expecter) Update(ctx interface{}, old interface{}, next interface{}) *MockDatastoresService_Update_Call {
	return &MockDatastoresService_Update_Call{Call: _e.mock.On("Update", ctx, old, next)}
}

func (_c *MockDatastoresService_Update_Call) Run(run func(ctx context.Context, old Datastore, next Datastore)) *MockDatastoresService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Datastore
		if args[1] != nil {
			arg1 = args[1].(Datastore)
		}
		var arg2 Datastore
		if args[2] != nil {
			arg2 = args[2].(Datastore)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastoresService_Update_Call) Return(datastore *Datastore, err error) *MockDatastoresService_Update_Call {
	_c.Call.Return(datastore, err)
	return _c
}

func (_c *MockDatastoresService_Update_Call) RunAndReturn(run func(ctx context.Context, old Datastore, next Datastore) (*Datastore, error)) *MockDatastoresService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVPCsService creates a new instance of MockVPCsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVPCsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVPCsService {
	mock := &MockVPCsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVPCsService is an autogenerated mock type for the VPCsService type
type MockVPCsService struct {
	mock.Mock
}

type MockVPCsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVPCsService) EXPECT() *MockVPCsService_Expecter {
	return &MockVPCsService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVPCsService
func (_mock *MockVPCsService) Create(ctx context.Context, vpc VPC) (*VPC, error) {
	ret := _mock.Called(ctx, vpc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *VPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, VPC) (*VPC, error)); ok {
		return returnFunc(ctx, vpc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, VPC) *VPC); ok {
		r0 = returnFunc(ctx, vpc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, VPC) error); ok {
		r1 = returnFunc(ctx, vpc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVPCsService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVPCsService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - vpc VPC
func (_e *MockVPCsService_Expecter) Create(ctx interface{}, vpc interface{}) *MockVPCsService_Create_Call {
	return &MockVPCsService_Create_Call{Call: _e.mock.On("Create", ctx, vpc)}
}

func (_c *MockVPCsService_Create_Call) Run(run func(ctx context.Context, vpc VPC)) *MockVPCsService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VPC
		if args[1] != nil {
			arg1 = args[1].(VPC)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVPCsService_Create_Call) Return(vPC *VPC, err error) *MockVPCsService_Create_Call {
	_c.Call.Return(vPC, err)
	return _c
}

func (_c *MockVPCsService_Create_Call) RunAndReturn(run func(ctx context.Context, vpc VPC) (*VPC, error)) *MockVPCsService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVPCsService
func (_mock *MockVPCsService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVPCsService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVPCsService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVPCsService_Expecter) Delete(ctx interface{}, id interface{}) *MockVPCsService_Delete_Call {
	return &MockVPCsService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVPCsService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockVPCsService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVPCsService_Delete_Call) Return(err error) *MockVPCsService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVPCsService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockVPCsService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockVPCsService
func (_mock *MockVPCsService) Read(ctx context.Context, id string) (*VPC, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *VPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*VPC, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *VPC); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVPCsService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockVPCsService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVPCsService_Expecter) Read(ctx interface{}, id interface{}) *MockVPCsService_Read_Call {
	return &MockVPCsService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockVPCsService_Read_Call) Run(run func(ctx context.Context, id string)) *MockVPCsService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVPCsService_Read_Call) Return(vPC *VPC, err error) *MockVPCsService_Read_Call {
	_c.Call.Return(vPC, err)
	return _c
}

func (_c *MockVPCsService_Read_Call) RunAndReturn(run func(ctx context.Context, id string) (*VPC, error)) *MockVPCsService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVPCsService
func (_mock *MockVPCsService) Update(ctx context.Context, vpc VPC) (*VPC, error) {
	ret := _mock.Called(ctx, vpc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *VPC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, VPC) (*VPC, error)); ok {
		return returnFunc(ctx, vpc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, VPC) *VPC); ok {
		r0 = returnFunc(ctx, vpc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VPC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, VPC) error); ok {
		r1 = returnFunc(ctx, vpc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVPCsService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVPCsService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - vpc VPC
func (_e *MockVPCsService_Expecter) Update(ctx interface{}, vpc interface{}) *MockVPCsService_Update_Call {
	return &MockVPCsService_Update_Call{Call: _e.mock.On("Update", ctx, vpc)}
}

func (_c *MockVPCsService_Update_Call) Run(run func(ctx context.Context, vpc VPC)) *MockVPCsService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VPC
		if args[1] != nil {
			arg1 = args[1].(VPC)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVPCsService_Update_Call) Return(vPC *VPC, err error) *MockVPCsService_Update_Call {
	_c.Call.Return(vPC, err)
	return _c
}

func (_c *MockVPCsService_Update_Call) RunAndReturn(run func(ctx context.Context, vpc VPC) (*VPC, error)) *MockVPCsService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContentService creates a new instance of MockContentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentService {
	mock := &MockContentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentService is an autogenerated mock type for the ContentService type
type MockContentService struct {
	mock.Mock
}

type MockContentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentService) EXPECT() *MockContentService_Expecter {
	return &MockContentService_Expecter{mock: &_m.Mock}
}

// AvailabilityZones provides a mock function for the type MockContentService
func (_mock *MockContentService) AvailabilityZones(ctx context.Context, provider string, region string) ([]string, error) {
	ret := _mock.Called(ctx, provider, region)

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZones")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, provider, region)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, provider, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, region)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_AvailabilityZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZones'
type MockContentService_AvailabilityZones_Call struct {
	*mock.Call
}

// AvailabilityZones is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - region string
func (_e *MockContentService_Expecter) AvailabilityZones(ctx interface{}, provider interface{}, region interface{}) *MockContentService_AvailabilityZones_Call {
	return &MockContentService_AvailabilityZones_Call{Call: _e.mock.On("AvailabilityZones", ctx, provider, region)}
}

func (_c *MockContentService_AvailabilityZones_Call) Run(run func(ctx context.Context, provider string, region string)) *MockContentService_AvailabilityZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContentService_AvailabilityZones_Call) Return(strings []string, err error) *MockContentService_AvailabilityZones_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockContentService_AvailabilityZones_Call) RunAndReturn(run func(ctx context.Context, provider string, region string) ([]string, error)) *MockContentService_AvailabilityZones_Call {
	_c.Call.Return(run)
	return _c
}

// DBVendors provides a mock function for the type MockContentService
func (_mock *MockContentService) DBVendors(ctx context.Context) ([]DBVendorInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DBVendors")
	}

	var r0 []DBVendorInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]DBVendorInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []DBVendorInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DBVendorInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_DBVendors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBVendors'
type MockContentService_DBVendors_Call struct {
	*mock.Call
}

// DBVendors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContentService_Expecter) DBVendors(ctx interface{}) *MockContentService_DBVendors_Call {
	return &MockContentService_DBVendors_Call{Call: _e.mock.On("DBVendors", ctx)}
}

func (_c *MockContentService_DBVendors_Call) Run(run func(ctx context.Context)) *MockContentService_DBVendors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContentService_DBVendors_Call) Return(dBVendorInfos []DBVendorInfo, err error) *MockContentService_DBVendors_Call {
	_c.Call.Return(dBVendorInfos, err)
	return _c
}

func (_c *MockContentService_DBVendors_Call) RunAndReturn(run func(ctx context.Context) ([]DBVendorInfo, error)) *MockContentService_DBVendors_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceSizes provides a mock function for the type MockContentService
func (_mock *MockContentService) InstanceSizes(ctx context.Context) (map[string][]InstanceSize, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InstanceSizes")
	}

	var r0 map[string][]InstanceSize
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string][]InstanceSize, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string][]InstanceSize); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]InstanceSize)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_InstanceSizes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceSizes'
type MockContentService_InstanceSizes_Call struct {
	*mock.Call
}

// InstanceSizes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContentService_Expecter) InstanceSizes(ctx interface{}) *MockContentService_InstanceSizes_Call {
	return &MockContentService_InstanceSizes_Call{Call: _e.mock.On("InstanceSizes", ctx)}
}

func (_c *MockContentService_InstanceSizes_Call) Run(run func(ctx context.Context)) *MockContentService_InstanceSizes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContentService_InstanceSizes_Call) Return(stringToInstanceSizes map[string][]InstanceSize, err error) *MockContentService_InstanceSizes_Call {
	_c.Call.Return(stringToInstanceSizes, err)
	return _c
}

func (_c *MockContentService_InstanceSizes_Call) RunAndReturn(run func(ctx context.Context) (map[string][]InstanceSize, error)) *MockContentService_InstanceSizes_Call {
	_c.Call.Return(run)
	return _c
}

// VolumeTypes provides a mock function for the type MockContentService
func (_mock *MockContentService) VolumeTypes(ctx context.Context, cloud string) ([]string, error) {
	ret := _mock.Called(ctx, cloud)

	if len(ret) == 0 {
		panic("no return value specified for VolumeTypes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, cloud)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, cloud)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cloud)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_VolumeTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VolumeTypes'
type MockContentService_VolumeTypes_Call struct {
	*mock.Call
}

// VolumeTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - cloud string
func (_e *MockContentService_Expecter) VolumeTypes(ctx interface{}, cloud interface{}) *MockContentService_VolumeTypes_Call {
	return &MockContentService_VolumeTypes_Call{Call: _e.mock.On("VolumeTypes", ctx, cloud)}
}

func (_c *MockContentService_VolumeTypes_Call) Run(run func(ctx context.Context, cloud string)) *MockContentService_VolumeTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentService_VolumeTypes_Call) Return(strings []string, err error) *MockContentService_VolumeTypes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockContentService_VolumeTypes_Call) RunAndReturn(run func(ctx context.Context, cloud string) ([]string, error)) *MockContentService_VolumeTypes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParameterGroupsService creates a new instance of MockParameterGroupsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParameterGroupsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParameterGroupsService {
	mock := &MockParameterGroupsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParameterGroupsService is an autogenerated mock type for the ParameterGroupsService type
type MockParameterGroupsService struct {
	mock.Mock
}

type MockParameterGroupsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParameterGroupsService) EXPECT() *MockParameterGroupsService_Expecter {
	return &MockParameterGroupsService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockParameterGroupsService
func (_mock *MockParameterGroupsService) Create(ctx context.Context, p ParameterGroup) (*ParameterGroup, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ParameterGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ParameterGroup) (*ParameterGroup, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ParameterGroup) *ParameterGroup); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ParameterGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ParameterGroup) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParameterGroupsService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockParameterGroupsService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p ParameterGroup
func (_e *MockParameterGroupsService_Expecter) Create(ctx interface{}, p interface{}) *MockParameterGroupsService_Create_Call {
	return &MockParameterGroupsService_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockParameterGroupsService_Create_Call) Run(run func(ctx context.Context, p ParameterGroup)) *MockParameterGroupsService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ParameterGroup
		if args[1] != nil {
			arg1 = args[1].(ParameterGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParameterGroupsService_Create_Call) Return(parameterGroup *ParameterGroup, err error) *MockParameterGroupsService_Create_Call {
	_c.Call.Return(parameterGroup, err)
	return _c
}

func (_c *MockParameterGroupsService_Create_Call) RunAndReturn(run func(ctx context.Context, p ParameterGroup) (*ParameterGroup, error)) *MockParameterGroupsService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockParameterGroupsService
func (_mock *MockParameterGroupsService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParameterGroupsService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockParameterGroupsService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockParameterGroupsService_Expecter) Delete(ctx interface{}, id interface{}) *MockParameterGroupsService_Delete_Call {
	return &MockParameterGroupsService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockParameterGroupsService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockParameterGroupsService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParameterGroupsService_Delete_Call) Return(err error) *MockParameterGroupsService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParameterGroupsService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockParameterGroupsService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockParameterGroupsService
func (_mock *MockParameterGroupsService) Read(ctx context.Context, id string) (*ParameterGroup, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *ParameterGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ParameterGroup, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ParameterGroup); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ParameterGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParameterGroupsService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockParameterGroupsService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockParameterGroupsService_Expecter) Read(ctx interface{}, id interface{}) *MockParameterGroupsService_Read_Call {
	return &MockParameterGroupsService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockParameterGroupsService_Read_Call) Run(run func(ctx context.Context, id string)) *MockParameterGroupsService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParameterGroupsService_Read_Call) Return(parameterGroup *ParameterGroup, err error) *MockParameterGroupsService_Read_Call {
	_c.Call.Return(parameterGroup, err)
	return _c
}

func (_c *MockParameterGroupsService_Read_Call) RunAndReturn(run func(ctx context.Context, id string) (*ParameterGroup, error)) *MockParameterGroupsService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockParameterGroupsService
func (_mock *MockParameterGroupsService) Update(ctx context.Context, p ParameterGroup) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ParameterGroup) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParameterGroupsService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParameterGroupsService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p ParameterGroup
func (_e *MockParameterGroupsService_Expecter) Update(ctx interface{}, p interface{}) *MockParameterGroupsService_Update_Call {
	return &MockParameterGroupsService_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockParameterGroupsService_Update_Call) Run(run func(ctx context.Context, p ParameterGroup)) *MockParameterGroupsService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ParameterGroup
		if args[1] != nil {
			arg1 = args[1].(ParameterGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParameterGroupsService_Update_Call) Return(err error) *MockParameterGroupsService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParameterGroupsService_Update_Call) RunAndReturn(run func(ctx context.Context, p ParameterGroup) error) *MockParameterGroupsService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobsService creates a new instance of MockJobsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobsService {
	mock := &MockJobsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobsService is an autogenerated mock type for the JobsService type
type MockJobsService struct {
	mock.Mock
}

type MockJobsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobsService) EXPECT() *MockJobsService_Expecter {
	return &MockJobsService_Expecter{mock: &_m.Mock}
}

// Await provides a mock function for the type MockJobsService
func (_mock *MockJobsService) Await(ctx context.Context, storeID string, job JobType) (JobStatus, error) {
	ret := _mock.Called(ctx, storeID, job)

	if len(ret) == 0 {
		panic("no return value specified for Await")
	}

	var r0 JobStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, JobType) (JobStatus, error)); ok {
		return returnFunc(ctx, storeID, job)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, JobType) JobStatus); ok {
		r0 = returnFunc(ctx, storeID, job)
	} else {
		r0 = ret.Get(0).(JobStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, JobType) error); ok {
		r1 = returnFunc(ctx, storeID, job)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobsService_Await_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Await'
type MockJobsService_Await_Call struct {
	*mock.Call
}

// Await is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - job JobType
func (_e *MockJobsService_Expecter) Await(ctx interface{}, storeID interface{}, job interface{}) *MockJobsService_Await_Call {
	return &MockJobsService_Await_Call{Call: _e.mock.On("Await", ctx, storeID, job)}
}

func (_c *MockJobsService_Await_Call) Run(run func(ctx context.Context, storeID string, job JobType)) *MockJobsService_Await_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 JobType
		if args[2] != nil {
			arg2 = args[2].(JobType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobsService_Await_Call) Return(jobStatus JobStatus, err error) *MockJobsService_Await_Call {
	_c.Call.Return(jobStatus, err)
	return _c
}

func (_c *MockJobsService_Await_Call) RunAndReturn(run func(ctx context.Context, storeID string, job JobType) (JobStatus, error)) *MockJobsService_Await_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockJobsService
func (_mock *MockJobsService) GetStatus(context1 context.Context, storeID string, job JobType) (JobStatus, error) {
	ret := _mock.Called(context1, storeID, job)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 JobStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, JobType) (JobStatus, error)); ok {
		return returnFunc(context1, storeID, job)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, JobType) JobStatus); ok {
		r0 = returnFunc(context1, storeID, job)
	} else {
		r0 = ret.Get(0).(JobStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, JobType) error); ok {
		r1 = returnFunc(context1, storeID, job)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobsService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockJobsService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - storeID string
//   - job JobType
func (_e *MockJobsService_Expecter) GetStatus(context1 interface{}, storeID interface{}, job interface{}) *MockJobsService_GetStatus_Call {
	return &MockJobsService_GetStatus_Call{Call: _e.mock.On("GetStatus", context1, storeID, job)}
}

func (_c *MockJobsService_GetStatus_Call) Run(run func(context1 context.Context, storeID string, job JobType)) *MockJobsService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 JobType
		if args[2] != nil {
			arg2 = args[2].(JobType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobsService_GetStatus_Call) Return(jobStatus JobStatus, err error) *MockJobsService_GetStatus_Call {
	_c.Call.Return(jobStatus, err)
	return _c
}

func (_c *MockJobsService_GetStatus_Call) RunAndReturn(run func(context1 context.Context, storeID string, job JobType) (JobStatus, error)) *MockJobsService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}
