inpackage: False
with-expecter: True
keeptree: False
filename: "{{.InterfaceName | snakecase | lower }}_mock.go"
mockname: "Mock{{.InterfaceName}}"
dir: "./internal/ccx/mocks"
outpkg: "mocks"

packages:
  "github.com/severalnines/terraform-provider-ccx/internal/ccx/api":
    interfaces:
      HttpClient: {}

  "github.com/severalnines/terraform-provider-ccx/internal/ccx":
    interfaces:
      DatastoreService: {}
      ContentService: {}
      VPCService: {}
      ParameterGroupService: {}
      JobService: {}