inpackage: False
with-expecter: True
keeptree: False
filename: "{{.InterfaceName | snakecase | lower }}_mock.go"
mockname: "Mock{{.InterfaceName}}"

packages:
  github.com/severalnines/terraform-provider-ccx/internal/ccx:
    interfaces:
      DatastoreService:
        config:
          dir: "./internal/ccx/mocks"
          outpkg: "mocks"
      ContentService:
        config:
          dir: "./internal/ccx/mocks"
          outpkg: "mocks"
      VPCService:
        config:
          dir: "./internal/ccx/mocks"
          outpkg: "mocks"
      ParameterGroupService:
        config:
          dir: "./internal/ccx/mocks"
          outpkg: "mocks"