// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	ccx "github.com/severalnines/terraform-provider-ccx/internal/ccx"

	mock "github.com/stretchr/testify/mock"
)

// MockJobService is an autogenerated mock type for the JobService type
type MockJobService struct {
	mock.Mock
}

type MockJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobService) EXPECT() *MockJobService_Expecter {
	return &MockJobService_Expecter{mock: &_m.Mock}
}

// Await provides a mock function with given fields: ctx, storeID, job
func (_m *MockJobService) Await(ctx context.Context, storeID string, job ccx.JobType) (ccx.JobStatus, error) {
	ret := _m.Called(ctx, storeID, job)

	if len(ret) == 0 {
		panic("no return value specified for Await")
	}

	var r0 ccx.JobStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ccx.JobType) (ccx.JobStatus, error)); ok {
		return rf(ctx, storeID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ccx.JobType) ccx.JobStatus); ok {
		r0 = rf(ctx, storeID, job)
	} else {
		r0 = ret.Get(0).(ccx.JobStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ccx.JobType) error); ok {
		r1 = rf(ctx, storeID, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_Await_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Await'
type MockJobService_Await_Call struct {
	*mock.Call
}

// Await is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - job ccx.JobType
func (_e *MockJobService_Expecter) Await(ctx interface{}, storeID interface{}, job interface{}) *MockJobService_Await_Call {
	return &MockJobService_Await_Call{Call: _e.mock.On("Await", ctx, storeID, job)}
}

func (_c *MockJobService_Await_Call) Run(run func(ctx context.Context, storeID string, job ccx.JobType)) *MockJobService_Await_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ccx.JobType))
	})
	return _c
}

func (_c *MockJobService_Await_Call) Return(_a0 ccx.JobStatus, _a1 error) *MockJobService_Await_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_Await_Call) RunAndReturn(run func(context.Context, string, ccx.JobType) (ccx.JobStatus, error)) *MockJobService_Await_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: _a0, storeID, job
func (_m *MockJobService) GetStatus(_a0 context.Context, storeID string, job ccx.JobType) (ccx.JobStatus, error) {
	ret := _m.Called(_a0, storeID, job)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 ccx.JobStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ccx.JobType) (ccx.JobStatus, error)); ok {
		return rf(_a0, storeID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ccx.JobType) ccx.JobStatus); ok {
		r0 = rf(_a0, storeID, job)
	} else {
		r0 = ret.Get(0).(ccx.JobStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ccx.JobType) error); ok {
		r1 = rf(_a0, storeID, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockJobService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - _a0 context.Context
//   - storeID string
//   - job ccx.JobType
func (_e *MockJobService_Expecter) GetStatus(_a0 interface{}, storeID interface{}, job interface{}) *MockJobService_GetStatus_Call {
	return &MockJobService_GetStatus_Call{Call: _e.mock.On("GetStatus", _a0, storeID, job)}
}

func (_c *MockJobService_GetStatus_Call) Run(run func(_a0 context.Context, storeID string, job ccx.JobType)) *MockJobService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ccx.JobType))
	})
	return _c
}

func (_c *MockJobService_GetStatus_Call) Return(_a0 ccx.JobStatus, _a1 error) *MockJobService_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_GetStatus_Call) RunAndReturn(run func(context.Context, string, ccx.JobType) (ccx.JobStatus, error)) *MockJobService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobService creates a new instance of MockJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobService {
	mock := &MockJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
