// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	ccx "github.com/severalnines/terraform-provider-ccx/internal/ccx"

	mock "github.com/stretchr/testify/mock"
)

// MockParameterGroupService is an autogenerated mock type for the ParameterGroupService type
type MockParameterGroupService struct {
	mock.Mock
}

type MockParameterGroupService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParameterGroupService) EXPECT() *MockParameterGroupService_Expecter {
	return &MockParameterGroupService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockParameterGroupService) Create(ctx context.Context, p ccx.ParameterGroup) (*ccx.ParameterGroup, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ccx.ParameterGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ccx.ParameterGroup) (*ccx.ParameterGroup, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ccx.ParameterGroup) *ccx.ParameterGroup); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ccx.ParameterGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ccx.ParameterGroup) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParameterGroupService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockParameterGroupService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p ccx.ParameterGroup
func (_e *MockParameterGroupService_Expecter) Create(ctx interface{}, p interface{}) *MockParameterGroupService_Create_Call {
	return &MockParameterGroupService_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockParameterGroupService_Create_Call) Run(run func(ctx context.Context, p ccx.ParameterGroup)) *MockParameterGroupService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ccx.ParameterGroup))
	})
	return _c
}

func (_c *MockParameterGroupService_Create_Call) Return(_a0 *ccx.ParameterGroup, _a1 error) *MockParameterGroupService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParameterGroupService_Create_Call) RunAndReturn(run func(context.Context, ccx.ParameterGroup) (*ccx.ParameterGroup, error)) *MockParameterGroupService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockParameterGroupService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockParameterGroupService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockParameterGroupService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockParameterGroupService_Expecter) Delete(ctx interface{}, id interface{}) *MockParameterGroupService_Delete_Call {
	return &MockParameterGroupService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockParameterGroupService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockParameterGroupService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockParameterGroupService_Delete_Call) Return(_a0 error) *MockParameterGroupService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockParameterGroupService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockParameterGroupService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id
func (_m *MockParameterGroupService) Read(ctx context.Context, id string) (*ccx.ParameterGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *ccx.ParameterGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ccx.ParameterGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ccx.ParameterGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ccx.ParameterGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParameterGroupService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockParameterGroupService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockParameterGroupService_Expecter) Read(ctx interface{}, id interface{}) *MockParameterGroupService_Read_Call {
	return &MockParameterGroupService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockParameterGroupService_Read_Call) Run(run func(ctx context.Context, id string)) *MockParameterGroupService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockParameterGroupService_Read_Call) Return(_a0 *ccx.ParameterGroup, _a1 error) *MockParameterGroupService_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParameterGroupService_Read_Call) RunAndReturn(run func(context.Context, string) (*ccx.ParameterGroup, error)) *MockParameterGroupService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockParameterGroupService) Update(ctx context.Context, p ccx.ParameterGroup) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ccx.ParameterGroup) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockParameterGroupService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParameterGroupService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p ccx.ParameterGroup
func (_e *MockParameterGroupService_Expecter) Update(ctx interface{}, p interface{}) *MockParameterGroupService_Update_Call {
	return &MockParameterGroupService_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockParameterGroupService_Update_Call) Run(run func(ctx context.Context, p ccx.ParameterGroup)) *MockParameterGroupService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ccx.ParameterGroup))
	})
	return _c
}

func (_c *MockParameterGroupService_Update_Call) Return(_a0 error) *MockParameterGroupService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockParameterGroupService_Update_Call) RunAndReturn(run func(context.Context, ccx.ParameterGroup) error) *MockParameterGroupService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParameterGroupService creates a new instance of MockParameterGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParameterGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParameterGroupService {
	mock := &MockParameterGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
