name: Lint
on: [push, pull_request]
permissions:
  contents: read
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check linting of Terraform files
      uses: devops-infra/action-tflint@v0.3
      
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run linters
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=30m
        version: v1.60